In [3]:
import pandas as pd
import re
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import statsmodels.api as sm
import numpy as np
from stargazer.stargazer import Stargazer

In [4]:
df = pd.read_parquet(r"C:\Users\Mateus Monteleone\Projects\ic\data\binary_model_table.parquet")

In [5]:
df.head()

,full_text,clean_text,unsupervised_sentiment,mentioned_candidates,mentions_lula,mentions_bolsonaro,mentions_tebet,mentions_ciro_gomes,is_economic
0,se o lula ganhar eu quero uma roda de beijo co...,se o lula ganhar eu quero uma roda de beijo co...,1.0,[lula],1,0,0,0,0
1,@ixslorena LULA PRESIDENTE HOJE,@USER LULA PRESIDENTE HOJE,0.0,[lula],1,0,0,0,0
2,mãe morrendo de alegria na carreata do Lula,mãe morrendo de alegria na carreata do Lula,0.0,[lula],1,0,0,0,0
3,@trajaza AVISA QUE MEU PAI LULA VAI GANHAR PRI...,@USER AVISA QUE MEU PAI LULA VAI GANHAR PRIMEI...,0.0,[lula],1,0,0,0,0
4,@indieoffw O RJ elegendo castro e juram que va...,@USER O RJ elegendo castro e juram que vai dar...,0.0,[lula],1,0,0,0,0

In [4]:
print(df.columns)

Index(['full_text', 'clean_text', 'unsupervised_sentiment',
       'mentioned_candidates', 'mentions_lula', 'mentions_bolsonaro',
       'mentions_tebet', 'mentions_ciro_gomes', 'is_economic'],
      dtype='object')

In [5]:
len(df)

190300

In [6]:
df["mentions_bolsonaro_and_economic"] = (
    (df["mentions_bolsonaro"] == 1) & (df["is_economic"] == 1)
).astype(int)

df["mentions_lula_and_economic"] = (
    (df["mentions_lula"] == 1) & (df["is_economic"] == 1)
).astype(int)

df["mentions_tebet_and_economic"] = (
    (df["mentions_tebet"] == 1) & (df["is_economic"] == 1)
).astype(int)

df["mentions_ciro_and_economic"] = (
    (df["mentions_ciro_gomes"] == 1) & (df["is_economic"] == 1)
).astype(int)

df[
    [
        "full_text",
        "clean_text",
        "unsupervised_sentiment",
        "is_economic",
        "mentions_lula",
        "mentions_bolsonaro",
        "mentions_tebet",
        "mentions_ciro_gomes",
        "mentions_bolsonaro_and_economic",
        "mentions_lula_and_economic",
        "mentions_tebet_and_economic",
        "mentions_ciro_and_economic",
    ]
].head()

,full_text,clean_text,unsupervised_sentiment,is_economic,mentions_lula,mentions_bolsonaro,mentions_tebet,mentions_ciro_gomes,mentions_bolsonaro_and_economic,mentions_lula_and_economic,mentions_tebet_and_economic,mentions_ciro_and_economic
0,se o lula ganhar eu quero uma roda de beijo co...,se o lula ganhar eu quero uma roda de beijo co...,1.0,0,1,0,0,0,0,0,0,0
1,@ixslorena LULA PRESIDENTE HOJE,@USER LULA PRESIDENTE HOJE,0.0,0,1,0,0,0,0,0,0,0
2,mãe morrendo de alegria na carreata do Lula,mãe morrendo de alegria na carreata do Lula,0.0,0,1,0,0,0,0,0,0,0
3,@trajaza AVISA QUE MEU PAI LULA VAI GANHAR PRI...,@USER AVISA QUE MEU PAI LULA VAI GANHAR PRIMEI...,0.0,0,1,0,0,0,0,0,0,0
4,@indieoffw O RJ elegendo castro e juram que va...,@USER O RJ elegendo castro e juram que vai dar...,0.0,0,1,0,0,0,0,0,0,0

In [7]:
binary_columns = [
    "is_economic",
    "mentions_lula",
    "mentions_bolsonaro",
    "mentions_tebet",
    "mentions_ciro_gomes",
    "mentions_lula_and_economic",
    "mentions_bolsonaro_and_economic",
    "mentions_tebet_and_economic",
    "mentions_ciro_and_economic",
]

for col in binary_columns:
    print(f"\n{col}")
    print(df[col].value_counts().sort_index())

is_economic
is_economic
0    186656
1      3644
Name: count, dtype: int64

mentions_lula
mentions_lula
0     71326
1    118974
Name: count, dtype: int64

mentions_bolsonaro
mentions_bolsonaro
0    114654
1     75646
Name: count, dtype: int64

mentions_tebet
mentions_tebet
0    186161
1      4139
Name: count, dtype: int64

mentions_ciro_gomes
mentions_ciro_gomes
0    170402
1     19898
Name: count, dtype: int64

mentions_lula_and_economic
mentions_lula_and_economic
0    188136
1      2164
Name: count, dtype: int64

mentions_bolsonaro_and_economic
mentions_bolsonaro_and_economic
0    188649
1      1651
Name: count, dtype: int64

mentions_tebet_and_economic
mentions_tebet_and_economic
0    190258
1        42
Name: count, dtype: int64

mentions_ciro_and_economic
mentions_ciro_and_economic
0    189882
1       418
Name: count, dtype: int64

In [8]:
X = df[binary_columns].copy()
y = df["unsupervised_sentiment"].copy()

In [9]:
X.head()

,is_economic,mentions_lula,mentions_bolsonaro,mentions_tebet,mentions_ciro_gomes,mentions_lula_and_economic,mentions_bolsonaro_and_economic,mentions_tebet_and_economic,mentions_ciro_and_economic
0,0,1,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0

In [22]:
X_sm = sm.add_constant(X)

# Modelo logit para sentimento positivo (y) binaria; x binaria p/ presidente_is_economic

logit_pos = sm.Logit((y == 1).astype(int), X_sm).fit()
result_positive = logit_pos
print("\nPOSITIVE MODEL")
print(result_positive.summary())

Optimization terminated successfully.
         Current function value: 0.639984
         Iterations 5

POSITIVE MODEL
                             Logit Regression Results
==================================================================================
Dep. Variable:     unsupervised_sentiment   No. Observations:               190300
Model:                              Logit   Df Residuals:                   190290
Method:                               MLE   Df Model:                            9
Date:                    Wed, 03 Jun 2026   Pseudo R-squ.:                 0.02274
Time:                            18:08:32   Log-Likelihood:            -1.2179e+05
converged:                           True   LL-Null:                   -1.2462e+05
Covariance Type:                nonrobust   LLR p-value:                     0.000
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                              -0.0286      0.017     -1.648      0.099      -0.063       0.005
is_economic                        -0.4552      0.122     -3.728      0.000      -0.694      -0.216
mentions_lula                      -0.2768      0.017    -16.641      0.000      -0.309      -0.244
mentions_bolsonaro                 -0.9069      0.016    -56.668      0.000      -0.938      -0.876
mentions_tebet                     -0.3929      0.037    -10.586      0.000      -0.466      -0.320
mentions_ciro_gomes                -0.0838      0.020     -4.180      0.000      -0.123      -0.045
mentions_lula_and_economic          0.0282      0.114      0.246      0.805      -0.196       0.252
mentions_bolsonaro_and_economic     0.1671      0.110      1.514      0.130      -0.049       0.383
mentions_tebet_and_economic        -0.3837      0.382     -1.005      0.315      -1.132       0.365
mentions_ciro_and_economic          0.7476      0.136      5.498      0.000       0.481       1.014
===================================================================================================

In [11]:
stargazer = Stargazer([result_positive])
stargazer.title("Logistic Regression Results")
stargazer

In [17]:
print("\nOdds Ratios - Positive")
print(np.exp(result_positive.params))

Odds Ratios - Positive
const                              0.971772
is_economic                        0.634347
mentions_lula                      0.758216
mentions_bolsonaro                 0.403757
mentions_tebet                     0.675073
mentions_ciro_gomes                0.919585
mentions_lula_and_economic         1.028596
mentions_bolsonaro_and_economic    1.181816
mentions_tebet_and_economic        0.681353
mentions_ciro_and_economic         2.112021
dtype: float64

In [ ]:
# Modelo logit binario para sentimento neutro (y) binaria; x binaria p/ presidentes + is_economic

logit_neu = sm.Logit((y == 0).astype(int), X_sm).fit()
result_neutral = logit_neu
print("Neutral Model: ")
print(result_neutral.summary())

Optimization terminated successfully.
         Current function value: 0.584539
         Iterations 7
Neutral Model:
                             Logit Regression Results
==================================================================================
Dep. Variable:     unsupervised_sentiment   No. Observations:               190300
Model:                              Logit   Df Residuals:                   190290
Method:                               MLE   Df Model:                            9
Date:                    Wed, 06 May 2026   Pseudo R-squ.:                 0.01138
Time:                            17:50:54   Log-Likelihood:            -1.1124e+05
converged:                           True   LL-Null:                   -1.1252e+05
Covariance Type:                nonrobust   LLR p-value:                     0.000
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                              -0.9957      0.017    -57.195      0.000      -1.030      -0.962
is_economic                        -0.9115      0.154     -5.911      0.000      -1.214      -0.609
mentions_lula                       0.1427      0.016      8.659      0.000       0.110       0.175
mentions_bolsonaro                  0.0441      0.016      2.798      0.005       0.013       0.075
mentions_tebet                      0.8537      0.037     22.796      0.000       0.780       0.927
mentions_ciro_gomes                -0.8139      0.024    -33.941      0.000      -0.861      -0.767
mentions_lula_and_economic         -0.1546      0.140     -1.101      0.271      -0.430       0.121
mentions_bolsonaro_and_economic     0.1594      0.138      1.156      0.248      -0.111       0.430
mentions_tebet_and_economic         0.8734      0.377      2.319      0.020       0.135       1.612
mentions_ciro_and_economic         -0.2023      0.239     -0.847      0.397      -0.670       0.266
===================================================================================================

In [19]:
print("\nOdds Ratios - Neutral")
print(np.exp(result_neutral.params))

Odds Ratios - Neutral
const                              0.369472
is_economic                        0.401909
mentions_lula                      1.153416
mentions_bolsonaro                 1.045043
mentions_tebet                     2.348270
mentions_ciro_gomes                0.443108
mentions_lula_and_economic         0.856763
mentions_bolsonaro_and_economic    1.172807
mentions_tebet_and_economic        2.395031
mentions_ciro_and_economic         0.816866
dtype: float64

In [20]:
# Modelo logit para sentimento negativo (y) binaria; x binaria p/ presidente_is_economic

logit_neg = sm.Logit((y == -1).astype(int), X_sm).fit()
result_negative = logit_neg
print("Negative Model: ")
print(result_negative.summary())

Optimization terminated successfully.
         Current function value: 0.634887
         Iterations 5
Negative Model:
                             Logit Regression Results
==================================================================================
Dep. Variable:     unsupervised_sentiment   No. Observations:               190300
Model:                              Logit   Df Residuals:                   190290
Method:                               MLE   Df Model:                            9
Date:                    Wed, 06 May 2026   Pseudo R-squ.:                 0.02769
Time:                            17:51:05   Log-Likelihood:            -1.2082e+05
converged:                           True   LL-Null:                   -1.2426e+05
Covariance Type:                nonrobust   LLR p-value:                     0.000
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                              -1.0660      0.016    -67.911      0.000      -1.097      -1.035
is_economic                         1.0190      0.108      9.425      0.000       0.807       1.231
mentions_lula                       0.1059      0.015      7.215      0.000       0.077       0.135
mentions_bolsonaro                  0.8184      0.014     57.218      0.000       0.790       0.846
mentions_tebet                     -0.3272      0.036     -9.065      0.000      -0.398      -0.256
mentions_ciro_gomes                 0.6354      0.019     33.360      0.000       0.598       0.673
mentions_lula_and_economic          0.1247      0.100      1.247      0.212      -0.071       0.321
mentions_bolsonaro_and_economic    -0.2964      0.097     -3.054      0.002      -0.487      -0.106
mentions_tebet_and_economic         0.0494      0.327      0.151      0.880      -0.591       0.690
mentions_ciro_and_economic         -0.9319      0.128     -7.271      0.000      -1.183      -0.681
===================================================================================================

In [21]:
print("\nOdds Ratios - Negative")
print(np.exp(result_negative.params))

Odds Ratios - Negative
const                              0.344377
is_economic                        2.770391
mentions_lula                      1.111667
mentions_bolsonaro                 2.266836
mentions_tebet                     0.720958
mentions_ciro_gomes                1.887746
mentions_lula_and_economic         1.132793
mentions_bolsonaro_and_economic    0.743492
mentions_tebet_and_economic        1.050639
mentions_ciro_and_economic         0.393811
dtype: float64